### ISSUE TITLE
Example configuration file

### ISSUE THREAD

**Issue by petergeorge1** [adjacentlink/letce2-plugin-lxc#1]
Can the release include an example configuration file?

**Comment by sgalgano** [comment]
We have a task to add documentation and a tutorial for this project which will cover both [letce2](https://github.com/adjacentlink/letce2) and the lxc plugin.

**Comment by sgalgano** [comment]
It took longer than we hoped to get a basic tutorial together. See https://github.com/adjacentlink/letce2-tutorial.
